import { type Cache, NoCache } from "@faceit/cache";
import { NonRateLimiter, type RateLimiter } from "../ratelimit";
import {
	ChampionshipsApi,
	GamesApi,
	HubsApi,
	LeaderboardsApi,
	LeaguesApi,
	MatchesApi,
	MatchmakingsApi,
	OrganizersApi,
	PlayersApi,
	RankingsApi,
	SearchApi,
	TeamsApi,
	TournamentsApi,
} from "./api";
import { Configuration, type ConfigurationParameters } from "./configuration";

export class Client {
	public configuration: Configuration;
	public rateLimiter: RateLimiter;
	public cache: Cache;
	public basePath: string;

	public championships: ChampionshipsApi;
	public games: GamesApi;
	public hubs: HubsApi;
	public leaderboards: LeaderboardsApi;
	public leagues: LeaguesApi;
	public matches: MatchesApi;
	public matchmakings: MatchmakingsApi;
	public organizers: OrganizersApi;
	public players: PlayersApi;
	public rankings: RankingsApi;
	public search: SearchApi;
	public teams: TeamsApi;
	public tournaments: TournamentsApi;

	public constructor(
		configuration: ConfigurationParameters & {
			rateLimiter?: RateLimiter;
			cache?: Cache;
			url?: string;
		},
	) {
		this.configuration = new Configuration(configuration);
		this.rateLimiter = configuration.rateLimiter ?? new NonRateLimiter();
		this.cache = configuration.cache ?? new NoCache();
		this.basePath = configuration.url ?? "https://open.faceit.com/data/v4";
		const args = [
			this.configuration,
			this.basePath,
			this.fetch.bind(this),
		] as const;
		this.championships = new ChampionshipsApi(...args);
		this.games = new GamesApi(...args);
		this.hubs = new HubsApi(...args);
		this.leaderboards = new LeaderboardsApi(...args);
		this.leagues = new LeaguesApi(...args);
		this.matches = new MatchesApi(...args);
		this.matchmakings = new MatchmakingsApi(...args);
		this.organizers = new OrganizersApi(...args);
		this.players = new PlayersApi(...args);
		this.rankings = new RankingsApi(...args);
		this.search = new SearchApi(...args);
		this.teams = new TeamsApi(...args);
		this.tournaments = new TournamentsApi(...args);
	}

	/// Rate limit fetches to the v4 API.
	///
	/// This `fetch` implementation is used by both the Swagger client as well
	/// as the `get` method below.
	protected async fetch(
		request: string | URL | Request,
		init: RequestInit = {},
	): Promise<Response> {
		let response = await this.cache.get(request, init);
		if (response !== undefined) {
			return response;
		} else {
			await this.rateLimiter.limit();
			response = await fetch(request, init);
			await this.cache.put(response, request, init);
			return response;
		}
	}

	/// Shorthand for retrieving the authorization header value.
	///
	/// This method is only used by the `get` implementation below. Each API
	/// client generated by Swagger uses its own logic similar to this.
	public get authorization(): string | undefined {
		return typeof this.configuration.apiKey === "function"
			? this.configuration.apiKey("Authorization")
			: this.configuration.apiKey;
	}

	/// Shorthand for executing a fetch request with the client's authorization.
	///
	/// Provides two shortcuts: the first is assigning the Authorizatio header
	/// based on the client's configuration, and the second is prepending the
	/// Faceit API url to requests that start with a /, e.g. "/matches". This
	/// is mostly for debugging.
	public get(
		request: string | URL | Request,
		init: RequestInit = {},
	): Promise<Response> {
		if (typeof request === "string" && request.startsWith("/")) {
			request = `${this.configuration.basePath}${request}`;
		}
		const authorization = this.authorization;
		if (authorization) {
			init.headers = new Headers(init.headers);
			init.headers.set("Authorization", this.authorization);
		}
		return this.fetch(request, init);
	}
}
